/**
 * db.ts — Typed database wrappers for the canonical-owner research tables.
 *
 * All functions accept a Supabase client (admin or server) so callers control
 * the security context.  None of these functions hit the DB in tests — pass a
 * mock client instead.
 */

import type { SupabaseClient } from "@supabase/supabase-js";

// ---------------------------------------------------------------------------
// Row types (mirrors 0023_canonical_owner_schema.sql)
// ---------------------------------------------------------------------------

export type OwnerType = "individual" | "numbered_co" | "named_co" | "trust" | "government";
export type DedupeStatus = "auto" | "human_confirmed" | "pending_review";

export interface CanonicalOwnerRow {
  owner_id: string;
  owner_type: OwnerType;
  canonical_name: string;
  canonical_name_normalized: string;
  neq: string | null;
  mailing_address_raw: string | null;
  mailing_geocode: unknown | null;
  mailing_postal_fsa: string | null;
  dedupe_status: DedupeStatus;
  is_aggregator_address: boolean;
  created_at: string;
  updated_at: string;
}

export interface EvidenceRow {
  evidence_id: string;
  owner_id: string;
  source: string;
  source_url: string | null;
  query_text: string | null;
  fetched_at: string;
  raw_response: Record<string, unknown> | null;
  structured: Record<string, unknown>;
  weight_at_fetch: number;
}

export type HypothesisClaimType = "phone" | "email" | "address";
export type HypothesisTier = "A" | "B" | "C" | "D" | "E";
export type HypothesisConfidenceLabel = "confirmed" | "likely" | "connected" | "weak";
export type HypothesisStatus = "candidate" | "accepted" | "rejected" | "superseded";

export interface HypothesisRow {
  hypothesis_id: string;
  owner_id: string;
  claim_type: HypothesisClaimType;
  claim_value: string;
  claim_value_e164: string | null;
  tier: HypothesisTier;
  confidence_label: HypothesisConfidenceLabel;
  is_direct: boolean;
  status: HypothesisStatus;
  status_reason: string | null;
  evidence_ids: string[];
  created_at: string;
  updated_at: string;
}

export interface OwnerRecordRow {
  record_id: string;
  owner_id: string;
  snapshot_hash: string;
  primary_phone_e164: string | null;
  primary_phone_tier: string | null;
  primary_phone_label: string | null;
  primary_phone_is_direct: boolean | null;
  alternate_phones: Record<string, unknown> | null;
  briefing_text: string | null;
  whats_interesting: string | null;
  property_matricules: string[] | null;
  audit_url: string | null;
  research_completed_at: string;
  published_to_crm: boolean;
  published_at: string | null;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyClient = SupabaseClient<any>;

// ---------------------------------------------------------------------------
// Evidence
// ---------------------------------------------------------------------------

/**
 * Insert a single evidence row.  `evidence_id` and `fetched_at` are generated
 * by the DB — omit them from the input.
 */
export async function insertEvidence(
  sb: AnyClient,
  e: Omit<EvidenceRow, "evidence_id" | "fetched_at">
): Promise<{ data: EvidenceRow | null; error: unknown }> {
  const { data, error } = await sb
    .from("evidence")
    .insert(e)
    .select()
    .single();
  return { data: data as EvidenceRow | null, error };
}

// ---------------------------------------------------------------------------
// Hypothesis
// ---------------------------------------------------------------------------

/**
 * Insert a single hypothesis row.  `hypothesis_id`, `created_at`, and
 * `updated_at` are generated by the DB — omit them from the input.
 */
export async function insertHypothesis(
  sb: AnyClient,
  h: Omit<HypothesisRow, "hypothesis_id" | "created_at" | "updated_at">
): Promise<{ data: HypothesisRow | null; error: unknown }> {
  const { data, error } = await sb
    .from("hypothesis")
    .insert(h)
    .select()
    .single();
  return { data: data as HypothesisRow | null, error };
}

// ---------------------------------------------------------------------------
// Owner record
// ---------------------------------------------------------------------------

/**
 * Upsert an owner_record row keyed on (owner_id, snapshot_hash).
 * `record_id` is generated by the DB — omit it from the input.
 */
export async function upsertOwnerRecord(
  sb: AnyClient,
  r: Omit<OwnerRecordRow, "record_id">
): Promise<{ data: OwnerRecordRow | null; error: unknown }> {
  const { data, error } = await sb
    .from("owner_record")
    .upsert(r, { onConflict: "owner_id,snapshot_hash" })
    .select()
    .single();
  return { data: data as OwnerRecordRow | null, error };
}

// ---------------------------------------------------------------------------
// Canonical owner lookup
// ---------------------------------------------------------------------------

/**
 * Fetch a single canonical_owner row by its primary key.
 */
export async function findCanonicalOwnerById(
  sb: AnyClient,
  ownerId: string
): Promise<{ data: CanonicalOwnerRow | null; error: unknown }> {
  const { data, error } = await sb
    .from("canonical_owner")
    .select("*")
    .eq("owner_id", ownerId)
    .single();
  return { data: data as CanonicalOwnerRow | null, error };
}
